[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo_solana = "3Dz8ofmvtfGHZhEXdqQSNftNbpnXJcUwrK231aamwDiD"

[programs.devnet]
todo_solana = "3Dz8ofmvtfGHZhEXdqQSNftNbpnXJcUwrK231aamwDiD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
